import React from "react";
import { Select } from "@mantine/core";

interface ICountrySelectProps {
    value?: string;
    label?: string;
    placeholder?: string;
    disabled?: boolean;
    required?: boolean;
    onChange: (value: string) => void;
}
export default function CountrySelect(props: ICountrySelectProps) {
    const data = [
        { value: "USX", label: "United States" },
        { value: "AFX", label: "Afghanistan" },
        { value: "ALX", label: "Albania" },
        { value: "DZX", label: "Algeria" },
        { value: "ASX", label: "American Samoa" },
        { value: "ADX", label: "Andorra" },
        { value: "AOX", label: "Angola" },
        { value: "AIX", label: "Anguilla" },
        { value: "AGX", label: "Antigua and Barbuda" },
        { value: "ARX", label: "Argentina" },
        { value: "AMX", label: "Armenia" },
        { value: "AWX", label: "Aruba" },
        { value: "AUX", label: "Australia" },
        { value: "ATX", label: "Austria" },
        { value: "AZX", label: "Azerbaijan" },
        { value: "BSX", label: "Bahamas" },
        { value: "BHX", label: "Bahrain" },
        { value: "BDX", label: "Bangladesh" },
        { value: "BBX", label: "Barbados" },
        { value: "BYX", label: "Belarus" },
        { value: "BEX", label: "Belgium" },
        { value: "BZX", label: "Belize" },
        { value: "BJX", label: "Benin" },
        { value: "BMX", label: "Bermuda" },
        { value: "BQX", label: "BES Islands" },
        { value: "BTX", label: "Bhutan" },
        { value: "BOX", label: "Bolivia" },
        { value: "BAX", label: "Bosnia and Herzegovina" },
        { value: "BWX", label: "Botswana" },
        { value: "BVX", label: "Bouvet Island" },
        { value: "BRX", label: "Brazil" },
        { value: "IOX", label: "British Indian Ocean Territory" },
        { value: "VGX", label: "British Virgin Islands" },
        { value: "BNX", label: "Brunei Darussalam" },
        { value: "BGX", label: "Bulgaria" },
        { value: "BFX", label: "Burkina Faso" },
        { value: "BIX", label: "Burundi" },
        { value: "CIX", label: "Côte d'Ivoire" },
        { value: "KHX", label: "Cambodia" },
        { value: "CMX", label: "Cameroon" },
        { value: "CAX", label: "Canada" },
        { value: "CVX", label: "Cabo Verde" },
        { value: "KYX", label: "Cayman Islands" },
        { value: "CFX", label: "Centralican Republic" },
        { value: "TDX", label: "Chad" },
        { value: "CLX", label: "Chile" },
        { value: "CNX", label: "China" },
        { value: "CXX", label: "Christmas Island" },
        { value: "CCX", label: "Cocos Islands" },
        { value: "COX", label: "Colombia" },
        { value: "KMX", label: "Comoros" },
        { value: "CGX", label: "Congo" },
        { value: "CKX", label: "Cook Islands" },
        { value: "CRX", label: "Costa Rica" },
        { value: "HRX", label: "Croatia" },
        { value: "CUX", label: "Cuba" },
        { value: "CWX", label: "Curacao" },
        { value: "CYX", label: "Cyprus" },
        { value: "CZX", label: "Czech Republic" },
        { value: "DKX", label: "Denmark" },
        { value: "DJX", label: "Djibouti" },
        { value: "DMX", label: "Dominica" },
        { value: "DOX", label: "Dominican Republic" },
        { value: "ECX", label: "Ecuador" },
        { value: "EGX", label: "Egypt" },
        { value: "SVX", label: "El Salvador" },
        { value: "GB2", label: "England" },
        { value: "GQX", label: "Equatorial Guinea" },
        { value: "ERX", label: "Eritrea" },
        { value: "EEX", label: "Estonia" },
        { value: "ETX", label: "Ethiopia" },
        { value: "FKX", label: "Falkland Islands" },
        { value: "FOX", label: "Faroe Islands" },
        { value: "FJX", label: "Fiji" },
        { value: "FIX", label: "Finland" },
        { value: "FRX", label: "France" },
        { value: "GFX", label: "French Guiana" },
        { value: "PFX", label: "French Polynesia" },
        { value: "GAX", label: "Gabon" },
        { value: "GMX", label: "Gambia" },
        { value: "GEX", label: "Georgia" },
        { value: "DEX", label: "Germany" },
        { value: "GHX", label: "Ghana" },
        { value: "GIX", label: "Gibraltar" },
        { value: "GB3", label: "Great Britain" },
        { value: "GRX", label: "Greece" },
        { value: "GLX", label: "Greenland" },
        { value: "GDX", label: "Grenada" },
        { value: "GPX", label: "Guadeloupe" },
        { value: "GUX", label: "Guam" },
        { value: "GTX", label: "Guatemala" },
        { value: "GGX", label: "Guernsey" },
        { value: "GNX", label: "Guinea" },
        { value: "GWX", label: "Guinea-Bissau" },
        { value: "GYX", label: "Guyana" },
        { value: "HTX", label: "Haiti" },
        { value: "HMX", label: "Heard Island and McDonald Islands" },
        { value: "HNX", label: "Honduras" },
        { value: "HKX", label: "Hong Kong" },
        { value: "HUX", label: "Hungary" },
        { value: "ISX", label: "Iceland" },
        { value: "INX", label: "India" },
        { value: "IDX", label: "Indonesia" },
        { value: "IRX", label: "Iran" },
        { value: "IQX", label: "Iraq" },
        { value: "IEX", label: "Ireland" },
        { value: "IMX", label: "Isle of Man" },
        { value: "ILX", label: "Israel" },
        { value: "ITX", label: "Italy" },
        { value: "JMX", label: "Jamaica" },
        { value: "JPX", label: "Japan" },
        { value: "JEX", label: "Jersey" },
        { value: "JTX", label: "Johnston Atoll" },
        { value: "JOX", label: "Jordan" },
        { value: "KZX", label: "Kazakhstan" },
        { value: "KEX", label: "Kenya" },
        { value: "KIX", label: "Kiribati" },
        { value: "KPX", label: "Korea, North" },
        { value: "KRX", label: "Korea, South" },
        { value: "KWX", label: "Kuwait" },
        { value: "KGX", label: "Kyrgyzstan" },
        { value: "LAX", label: "Laos" },
        { value: "LVX", label: "Latvia" },
        { value: "LBX", label: "Lebanon" },
        { value: "LSX", label: "Lesotho" },
        { value: "LRX", label: "Liberia" },
        { value: "LYX", label: "Libya" },
        { value: "LIX", label: "Liechtenstein" },
        { value: "LTX", label: "Lithuania" },
        { value: "LUX", label: "Luxembourg" },
        { value: "MOX", label: "Macau" },
        { value: "MKX", label: "Macedonia" },
        { value: "MGX", label: "Madagascar" },
        { value: "MWX", label: "Malawi" },
        { value: "MYX", label: "Malaysia" },
        { value: "MVX", label: "Maldives" },
        { value: "MLX", label: "Mali" },
        { value: "MTX", label: "Malta" },
        { value: "MHX", label: "Marshall Islands" },
        { value: "MQX", label: "Martinique" },
        { value: "MRX", label: "Mauritania" },
        { value: "MUX", label: "Mauritius" },
        { value: "YTX", label: "Mayotte" },
        { value: "MXX", label: "Mexico" },
        { value: "FMX", label: "Micronesia" },
        { value: "MDX", label: "Moldova" },
        { value: "MCX", label: "Monaco" },
        { value: "MNX", label: "Mongolia" },
        { value: "MSX", label: "Montserrat" },
        { value: "MAX", label: "Morocco" },
        { value: "MEX", label: "Montenegro" },
        { value: "MZX", label: "Mozambique" },
        { value: "MMX", label: "Myanmar" },
        { value: "NAX", label: "Namibia" },
        { value: "NRX", label: "Nauru" },
        { value: "NVX", label: "Navassa Island" },
        { value: "NPX", label: "Nepal" },
        { value: "NLX", label: "Netherlands" },
        { value: "NZX", label: "New Zealand" },
        { value: "NIX", label: "Nicaragua" },
        { value: "NEX", label: "Niger" },
        { value: "NGX", label: "Nigeria" },
        { value: "GB5", label: "Northern Ireland" },
        { value: "MPX", label: "Northern Mariana Islands" },
        { value: "NOX", label: "Norway" },
        { value: "OMX", label: "Oman" },
        { value: "PKX", label: "Pakistan" },
        { value: "PWX", label: "Palau" },
        { value: "PAX", label: "Panama" },
        { value: "PGX", label: "Papua New Guinea" },
        { value: "PYX", label: "Paraguay" },
        { value: "PEX", label: "Peru" },
        { value: "PHX", label: "Philippines" },
        { value: "PLX", label: "Poland" },
        { value: "PTX", label: "Portugal" },
        { value: "PRX", label: "Puerto Rico" },
        { value: "QAX", label: "Qatar" },
        { value: "ROX", label: "Romania" },
        { value: "RUX", label: "Russia" },
        { value: "RWX", label: "Rwanda" },
        { value: "KNX", label: "Saint Kitts and Nevis" },
        { value: "LCX", label: "Saint Lucia" },
        { value: "VCX", label: "Saint Vincent and Grenadines" },
        { value: "OOX", label: "Samoa" },
        { value: "SMX", label: "San Marino" },
        { value: "STX", label: "Sao Tome and Principe" },
        { value: "SAX", label: "Saudi Arabia" },
        { value: "GB6", label: "Scotland" },
        { value: "SNX", label: "Senegal" },
        { value: "RSX", label: "Serbia" },
        { value: "SCX", label: "Seychelles" },
        { value: "SLX", label: "Sierra Leone" },
        { value: "SGX", label: "Singapore" },
        { value: "SKX", label: "Slovakia" },
        { value: "SIX", label: "Slovenia" },
        { value: "SBX", label: "Solomon Islands" },
        { value: "SOX", label: "Somalia" },
        { value: "ZAX", label: "South Africa" },
        { value: "ESX", label: "Spain" },
        { value: "LKX", label: "Sri Lanka" },
        { value: "SXX", label: "St. Maarten" },
        { value: "SDX", label: "Sudan" },
        { value: "SRX", label: "Suriname" },
        { value: "SZX", label: "Swaziland" },
        { value: "SEX", label: "Sweden" },
        { value: "CHX", label: "Switzerland" },
        { value: "SYX", label: "Syria" },
        { value: "TWX", label: "Taiwan" },
        { value: "TJX", label: "Tajikistan" },
        { value: "TZX", label: "Tanzania" },
        { value: "THX", label: "Thailand" },
        { value: "TLX", label: "Timor-Leste" },
        { value: "TGX", label: "Togo" },
        { value: "TOX", label: "Tonga" },
        { value: "TTX", label: "Trinidad and Tobago" },
        { value: "TNX", label: "Tunisia" },
        { value: "TRX", label: "Turkey" },
        { value: "TMX", label: "Turkmenistan" },
        { value: "TCX", label: "Turks/Caicos Islands" },
        { value: "TVX", label: "Tuvalu" },
        { value: "UGX", label: "Uganda" },
        { value: "UAX", label: "Ukraine" },
        { value: "AEX", label: "United Arab Emirates" },
        { value: "GBX", label: "United Kingdom" },
        { value: "USA", label: "United States" },
        { value: "UYX", label: "Uruguay" },
        { value: "VIX", label: "US Virgin Islands" },
        { value: "UZX", label: "Uzbekistan" },
        { value: "VUX", label: "Vanuatu" },
        { value: "VAX", label: "Vatican City" },
        { value: "VEX", label: "Venezuela" },
        { value: "VNX", label: "Vietnam" },
        { value: "WKX", label: "Wake Island" },
        { value: "GB7", label: "Wales" },
        { value: "WFX", label: "Wallis and Futuna" },
        { value: "PSX", label: "West Bank/Gaza" },
        { value: "EHX", label: "Western Sahara" },
        { value: "YEX", label: "Yemen" },
        { value: "ZMX", label: "Zambia" },
        { value: "ZWX", label: "Zimbabwe" }
    ];

    return (
        <Select
            label={props.label ?? "Country/Region/Jurisdiction"}
            placeholder={props.placeholder ?? "Country/Region/Jurisdiction"}
            searchable
            disabled={props.disabled}
            required={props.required}
            value={props.value}
            data={data}
            onChange={props.onChange}
        />
    );
}
